version: '3'

services:
  message-db:
    image: ethangarofolo/message-db:1.1.6
    ports:
      - '0.0.0.0:5432:5432'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '0.0.0.0:5433:5432'
